# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
# Fabric Properties
yarn_mappings=1.21.8+build.1
loader_version=0.17.2
# Mod Properties
mod_version=4.1.0-p4
maven_group=net.litetex.mcm
archivesBaseName=cape-provider-x
mod_name=Cape Provider X superJK92 Fork
mod_desc=Fork of Cape Provider Mod with tweaks by xsyanic and extended providers (PiCapes, SkinMC, etc.) (With Voidecube Capes, and CapeMod Capes)
mod_license_spdx_id=LGPL-2.1-or-later
mod_license_url=https://www.gnu.org/licenses/old-licenses/lgpl-2.1.html
# Additional
fabric_api_version=0.132.0+1.21.8
modmenu_version=15.0.0
skinshuffle_version=2.9.4+1.21.6
cicada_version=0.14.2+1.21.6-and-above
minecraftcapes_version=fabric-1.21.8-12.4.0
